spring:
  datasource:
    url: jdbc:h2:mem:storagedb

  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: false

    hibernate:
      ddl-auto: none

    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml

issue:
  max-days: 14
