spring:
  application:
    name: storage-backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/storage}
    username: ${DB_USER:storage}
    password: ${DB_PASSWORD:storage}
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: false

    hibernate:
      ddl-auto: none

    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml

issue:
  max-days: 14

server:
  port: 8080
