--
-- PostgreSQL database dump
--


-- Dumped from database version 16.15
-- Dumped by pg_dump version 16.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.category (
    id bigint NOT NULL,
    category_name character varying(100) NOT NULL
);


--
-- Name: category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employee; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employee (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    code character varying(100) NOT NULL,
    department character varying(100),
    photo_url character varying(255)
);


--
-- Name: employee_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: equipment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.equipment (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    inventory_code character varying(50) NOT NULL,
    description character varying(500),
    photo_url character varying(255),
    status character varying(20) NOT NULL,
    category_id bigint NOT NULL
);


--
-- Name: equipment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.equipment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: issue; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.issue (
    id bigint NOT NULL,
    issue_date date NOT NULL,
    return_date date NOT NULL,
    returned_at date,
    employee_id bigint NOT NULL,
    equipment_id bigint NOT NULL
);


--
-- Name: issue_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.issue ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.issue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: category; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.category (id, category_name) FROM stdin;
1	Ноутбуки
2	Проекторы
3	Камеры
4	Аксессуары
\.


--
-- Data for Name: employee; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.employee (id, name, code, department, photo_url) FROM stdin;
1	Orlov Dmitry	1111	Разработка	https://i.pravatar.cc/300?img=12
2	Sokolova Maria	2222	Маркетинг	https://i.pravatar.cc/300?img=47
3	Belov Artem	3333	Разработка	https://i.pravatar.cc/300?img=33
4	Nikitina Elena	4444	Бухгалтерия	https://i.pravatar.cc/300?img=25
\.


--
-- Data for Name: equipment; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.equipment (id, name, inventory_code, description, photo_url, status, category_id) FROM stdin;
1	MacBook Pro 14	EQ-000101	M3 Pro, 18 GB, 512 GB	https://picsum.photos/seed/eq101/400	AVAILABLE	1
2	MacBook Air 13	EQ-000102	M2, 16 GB, 256 GB	https://picsum.photos/seed/eq102/400	ISSUED	1
3	ThinkPad T14	EQ-000103	i7, 16 GB, 512 GB, Linux	https://picsum.photos/seed/eq103/400	AVAILABLE	1
4	Epson EB-X51	EQ-000201	XGA, 3800 лм, HDMI	https://picsum.photos/seed/eq201/400	AVAILABLE	2
5	Xiaomi Mi Smart Projector 2	EQ-000202	Full HD, Android TV	https://picsum.photos/seed/eq202/400	ISSUED	2
6	Sony A6400	EQ-000301	Kit 16-50, 2 батареи	https://picsum.photos/seed/eq301/400	AVAILABLE	3
7	GoPro Hero 11	EQ-000302	Крепление на голову в комплекте	https://picsum.photos/seed/eq302/400	BROKEN	3
8	Переходник USB-C - HDMI	EQ-000401		https://picsum.photos/seed/eq401/400	AVAILABLE	4
9	Переходник USB-C - HDMI	EQ-000402		https://picsum.photos/seed/eq402/400	AVAILABLE	4
10	Кликер Logitech R500	EQ-000403		https://picsum.photos/seed/eq403/400	AVAILABLE	4
\.


--
-- Data for Name: issue; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.issue (id, issue_date, return_date, returned_at, employee_id, equipment_id) FROM stdin;
1	2026-02-02	2026-02-09	2026-02-08	1	1
2	2026-02-05	2026-02-19	\N	1	2
3	2026-02-06	2026-02-08	\N	2	5
\.


--
-- Name: category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.category_id_seq', 4, true);


--
-- Name: employee_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.employee_id_seq', 4, true);


--
-- Name: equipment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.equipment_id_seq', 10, true);


--
-- Name: issue_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.issue_id_seq', 3, true);


--
-- Name: category category_category_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_category_name_key UNIQUE (category_name);


--
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);


--
-- Name: employee employee_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_code_key UNIQUE (code);


--
-- Name: employee employee_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_pkey PRIMARY KEY (id);


--
-- Name: equipment equipment_inventory_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT equipment_inventory_code_key UNIQUE (inventory_code);


--
-- Name: equipment equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT equipment_pkey PRIMARY KEY (id);


--
-- Name: issue issue_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issue
    ADD CONSTRAINT issue_pkey PRIMARY KEY (id);


--
-- Name: equipment fk_equipment_category; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT fk_equipment_category FOREIGN KEY (category_id) REFERENCES public.category(id);


--
-- Name: issue fk_issue_employee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issue
    ADD CONSTRAINT fk_issue_employee FOREIGN KEY (employee_id) REFERENCES public.employee(id);


--
-- Name: issue fk_issue_equipment; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issue
    ADD CONSTRAINT fk_issue_equipment FOREIGN KEY (equipment_id) REFERENCES public.equipment(id);


--
-- PostgreSQL database dump complete
--


